spring:
  application.name: SpringWork

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${rds.naverid}
            client-secret: ${rds.naversecret}
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: ${rds.naveruri}

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}


  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8070

jwt:
  secret: ${rds.jwttoken}

cors:
  allowed-origins: http://43.201.136.217:3000

app:
  pagination:
    write_pages: 10
    page_rows: 10

  upload:
    path: upload

  oauth2:
    password: 1234

    kakao:
      client-id: ${rds.kakaoid}
      redirect-uri: ${rds.kakaouri}
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

  from: ${rds.authenticationemail}
  password: ${rds.authenticationpassword}

naver:
  api:
    client-id: ${rds.newsapiid}
    client-secret: ${rds.newsapikey}